#!/usr/bin/env ruby

git_bundles = [
  "git://github.com/vim-scripts/ZoomWin.git",
  "git://git.wincent.com/command-t.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/vim-scripts/ack.vim.git",
  "git://github.com/Lokaltog/vim-powerline.git",
  "git://github.com/vim-scripts/bufexplorer.zip.git",
  "git://github.com/vim-scripts/VimClojure.git",
  "git://github.com/vim-scripts/screen.vim.git",
  "git://github.com/jayed/slimv.git",
  "git://github.com/briancollins/vim-jst.git",
  "git://github.com/nono/vim-handlebars.git",
  "git://github.com/wgibbs/vim-irblack.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tpope/vim-cucumber.git",
  "https://github.com/skwp/vim-rspec.git",
  "https://github.com/cakebaker/scss-syntax.vim.git",
  "https://github.com/mmalecki/vim-node.js.git",
  "https://github.com/ervandew/supertab.git",
]

vim_org_scripts = [
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

# Compile Command-T
`cd ~/.vim/bundle/command-t && rake make`

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
