# use vim as an editor
export EDITOR="mvim -f"

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# use incremental search
bindkey '^R' history-incremental-search-backward

# expand functions in the prompt
setopt prompt_subst

# prompt
export PS1='[${SSH_CONNECTION+"%n@%m:"}%~] '

# ignore duplicate history entries
setopt histignoredups

export PATH=/Users/bnferguson/dev/chromium/depot_tools:~/bin:/usr/local/sbin:/usr/local/git/libexec/git-core/:/usr/local/bin:/opt/local/bin:/usr/local/mysql/bin/:$EC2_HOME/bin:$PATH:~/dev/util/jruby/bin

cdpath=(~/dev)

source ~/.dotfiles/zsh/base.zsh
